# Generated by Django 6.1.1 on 2026-09-20 17:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('telefono', models.CharField(blank=True, default='', max_length=15, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electrónico')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej. Negro, Blanco, Azul.', max_length=30, unique=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Razón social o nombre comercial del proveedor.', max_length=100, unique=True, verbose_name='nombre')),
                ('telefono', models.CharField(blank=True, default='', max_length=15, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electrónico')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(default=0, verbose_name='unidades')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='tienda.color')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, verbose_name='modelo')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, verbose_name='descripción')),
                ('tipo', models.CharField(choices=[('PLAYERA', 'Playera'), ('CAMISA', 'Camisa'), ('PANTALON', 'Pantalón'), ('SHORT', 'Short'), ('VESTIDO', 'Vestido'), ('FALDA', 'Falda'), ('SUDADERA', 'Sudadera'), ('CHAMARRA', 'Chamarra'), ('OTRO', 'Otro')], default='OTRO', max_length=10, verbose_name='tipo')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio')),
                ('talla', models.CharField(choices=[('U', 'Unitalla'), ('CH', 'Chica'), ('M', 'Mediana'), ('G', 'Grande'), ('XG', 'Extra grande')], default='U', max_length=2, verbose_name='talla')),
                ('colores', models.ManyToManyField(related_name='prendas', through='tienda.Inventario', to='tienda.color')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='tienda.proveedor')),
            ],
            options={
                'verbose_name': 'prenda',
                'verbose_name_plural': 'ropa',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='ropa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='tienda.ropa'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('ropa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='tienda.ropa')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de venta',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='tienda.cliente')),
                ('prendas', models.ManyToManyField(related_name='ventas', through='tienda.DetalleVenta', to='tienda.ropa')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.venta'),
        ),
        migrations.AddConstraint(
            model_name='ropa',
            constraint=models.UniqueConstraint(fields=('modelo', 'marca', 'talla'), name='ropa_modelo_marca_talla_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('ropa', 'color'), name='inventario_ropa_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.UniqueConstraint(fields=('venta', 'ropa'), name='detalleventa_venta_ropa_uniq'),
        ),
    ]
